CREATE DATABASE[SalesDB] ON PRIMARY
(NAME= 'SaleDB',FILENAME ='C:\ProgramFile\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\DATA\SalesDB.mdf',SIZE=3072KB,MAXSIZE=UNLIMITED,FILEGRWTH= 1024KB),
FILEGROUP[ MyFileGroup]
(NAME ='SalesDB_FG',FILENAME='C:\ProgramFile\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\DATA\SalesDB.mdf',SIZE=3072KB,MAXSIZE=UNLIMITED,FILEGRWTH= 1024KB)